package http

type rounding struct {
	Base    int32
	Counter int32
}

// to generate:
// curl -s https://www.bitstamp.net/api/v2/trading-pairs-info/ | jq -r '.[] | "\"\(.url_symbol)\": {\(.base_decimals), \(.counter_decimals)},"' | sort
var roundings = map[string]rounding{
	"aavebtc":  {8, 8},
	"aaveeur":  {8, 2},
	"aaveusd":  {8, 2},
	"algobtc":  {8, 8},
	"algoeur":  {8, 5},
	"algousd":  {8, 5},
	"audiobtc": {8, 8},
	"audioeur": {8, 5},
	"audiousd": {8, 5},
	"batbtc":   {8, 8},
	"bateur":   {8, 5},
	"batusd":   {8, 5},
	"bchbtc":   {8, 8},
	"bcheur":   {8, 2},
	"bchgbp":   {8, 2},
	"bchusd":   {8, 2},
	"btceur":   {8, 2},
	"btcgbp":   {8, 2},
	"btcpax":   {8, 2},
	"btcusd":   {8, 2},
	"btcusdc":  {8, 2},
	"btcusdt":  {8, 2},
	"compbtc":  {8, 8},
	"compeur":  {8, 2},
	"compusd":  {8, 2},
	"crvbtc":   {8, 8},
	"crveur":   {8, 5},
	"crvusd":   {8, 5},
	"daiusd":   {5, 5},
	"eth2eth":  {8, 8},
	"ethbtc":   {8, 8},
	"etheur":   {8, 2},
	"ethgbp":   {8, 2},
	"ethpax":   {8, 2},
	"ethusd":   {8, 2},
	"ethusdc":  {8, 2},
	"ethusdt":  {8, 2},
	"eurusd":   {5, 5},
	"gbpeur":   {5, 5},
	"gbpusd":   {5, 5},
	"grteur":   {8, 5},
	"grtusd":   {8, 5},
	"gusdusd":  {5, 5},
	"kncbtc":   {8, 8},
	"knceur":   {8, 5},
	"kncusd":   {8, 5},
	"linkbtc":  {8, 8},
	"linketh":  {8, 8},
	"linkeur":  {8, 2},
	"linkgbp":  {8, 2},
	"linkusd":  {8, 2},
	"ltcbtc":   {8, 8},
	"ltceur":   {8, 2},
	"ltcgbp":   {8, 2},
	"ltcusd":   {8, 2},
	"mkrbtc":   {8, 8},
	"mkreur":   {8, 2},
	"mkrusd":   {8, 2},
	"omgbtc":   {8, 8},
	"omgeur":   {8, 2},
	"omggbp":   {8, 2},
	"omgusd":   {8, 2},
	"paxeur":   {5, 5},
	"paxgbp":   {5, 5},
	"paxusd":   {5, 5},
	"snxbtc":   {8, 8},
	"snxeur":   {8, 5},
	"snxusd":   {8, 5},
	"umabtc":   {8, 8},
	"umaeur":   {8, 2},
	"umausd":   {8, 2},
	"unibtc":   {8, 8},
	"unieur":   {8, 5},
	"uniusd":   {8, 5},
	"usdceur":  {5, 5},
	"usdcusd":  {5, 5},
	"usdcusdt": {5, 5},
	"usdteur":  {5, 5},
	"usdtusd":  {5, 5},
	"xlmbtc":   {8, 8},
	"xlmeur":   {8, 5},
	"xlmgbp":   {8, 5},
	"xlmusd":   {8, 5},
	"xrpbtc":   {8, 8},
	"xrpeur":   {8, 5},
	"xrpgbp":   {8, 5},
	"xrppax":   {8, 5},
	"xrpusd":   {8, 5},
	"xrpusdt":  {8, 5},
	"yfibtc":   {8, 8},
	"yfieur":   {8, 2},
	"yfiusd":   {8, 2},
	"zrxbtc":   {8, 8},
	"zrxeur":   {8, 5},
	"zrxusd":   {8, 5},
}
