name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.22

      - name: Format
        uses: Jerome1337/gofmt-action@v1.0.5

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
